### ISSUE TITLE
PEPFuture journals now part of PEPArchive and PEPCurrent

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PaDS#18]
FYI, I'm in the process of setting everything up to be transitioned per our annual plan, to production on Jan 22.  This weekend, finishing up this morning, I reprocessed all the data per below so the following should be reflected by the server on Stage.  

For the 2022 build now on Stage:
   - I've moved another year from PEPCurrent for each applicable journal out of that "embargo" into the PEPArchive category.  The server's response, based on the location in those special hierarchies we discussed, should be carried forward in the database and the servers response should reflect that.  
   - all of the PEPFuture journals have been moved into PEPCurrent and PEPArchive as appropriate by year and embargo length.
       - PCAS was moved, but we may move it back to PEPFuture since there's so little data.  Nadine and I need to talk about it to decide.
      - other than PCAS, potentially, the PEP Future messaging, as I've mentioned in a previous communication, looked good, but now only applies to when we do this next year and we actually push future data to production.  This year we couldn't do it because we haven't been able to do pushes without disruption.

My goal is to freeze all development and data by the 14th, giving D and his team a week to test and approve the release for the 22nd, or to delay it.

Issue: It may be related to needing the daily scans of contents from PaDS to the server, but I note that the new data still shows a PEPFuture warning, even though it's now become part of PEPArchive on the server.  If that's not it, perhaps we can talk tomorrow morning (Wednesday) and work this out?

**Comment by jwoosnam** [comment]
The population of the pads stage content database from OPAS, was last run on the 8th of January.

I have set it off again now so by the time you start work it should be up to date! I am around this afternoon if you want to discuss.

**Comment by nrshapiro** [comment]
I see the issue...the RDS product table for journals on Stage was not updated (and that's where the journal metadata comes from, rather than the Solr database, which covers the article level, where I was looking!).  I'm going to put a test in to catch that.

I know you and Leyla are working on automatic triggering, but until that's ready, if it's easy and you can retrigger the scan now that I've updated the table, please do.

**Comment by jwoosnam** [comment]
PaDS Stage has now been updated to v06.21a, this incorporated access classification support into the ContentSets and therefore lets admin user see all content.
