### ISSUE TITLE
Pads calling Opas Server without Session ID

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PaDS#19]
The server error log is generally quiet these days.  However, when PaDS calls to get metadata, it isn't sending a session ID and the log fills with these calls.  More importantly, for each of those calls, the server then calls Pads to get a session ID and each one is "generated" anew!

Can you check to see if you are not including one, or if you are, send me a sample of the call parameters and headers (I can't trace on AWS)?

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/4837554/149945137-a8ccc6cc-01e1-4e05-a8a1-b0f57fc6715e.png">

**Comment by jwoosnam** [comment]
I can confirm that I am NOT sending a session ID. Where would you like me to include it?
This is an example of the main metadata call:
https://stage-api.pep-web.org/v2/Metadata/Contents/ADPSA/1/?limit=10000

I also do the session call every hour:
https://stage-api.pep-web.org/v2/Admin/Reports/Session-Log?startdate=20220118123209&limit=50000&offset=0&download=false&sortorder=asc

Neither of these have ever passed a session Id.  What is it used for? And would it need to be Authenticated?

**Comment by nrshapiro** [comment]
1.  As to the Metadata/Contents call, session id is not 'required'.  But since now I track logged in and non logged in user activity, and the key for that is session id in the endpoint tables (and the session table), when I don't get one, I get one from PaDS.  But that means in your case there are hundreds(?) of session ids requested of PaDS while you are grabbing metadata.  

And I recently started warning type logging when there's no session id that since I've seen what looks like hacking type queries against the server.  And that's the source of all those log entries.  But more consequential than flooding the logs, it also makes numerous calls back to PaDS to get a new session id.

I could turn off all tracking on the metadata calls, but then I wouldn't know if it's being abused.  

I could alternatively require the API key in cases like this where you really don't need to be logged in.  But given the use of API key here, it would be **required** of any call.  Maybe that is more appropriate, especially in gathering journal and article data.  And it would not only track but prevent hacking/information gathering type calls.

Let me know what you think--either way you'd need to make a change.  Session ids can be supplied in the header, in a cookie, or in the URL.  So can API_KEYS.  (Less secure in the URL).  You should supply a client ID in either case.

2.  On the other hand, if you can make an admin level call (v2/Admin) every hour without a session id, I'm at a loss for words.

https://stage-api.pep-web.org/v2/Admin/Reports/Session-Log?startdate=20220118123209&limit=50000&offset=0&download=false&sortorder=asc

This requires admin authorization--which the server gets from PaDS based on the session id!  So even without checking the code, I am pretty certain you must be supplying one for that call.  You would get an error back from the server if you didn't supply a session id.  Let me know if somehow you are doing it!

**Comment by jwoosnam** [comment]
Your right client-session for an admin user is being passed for session log calls. I will pass it in the header for content calls.
