### ISSUE TITLE
Removing Offsite Books from our book list

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PaDS#23]
@jwoosnam @rickardnyman 

In my QA I realize that the two books by Kohut:

https://stage.pep-web.org/browse/document/ZBK.049.0001A
https://stage.pep-web.org/browse/document/ZBK.034.0001A

are offsite books which I am inadvertently handling differently than we used to.  We have the full-text of these books in the database, so they may show up in any search results, but we have never before included them in the list of books in PEP as they show here: 

<img width="232" alt="image" src="https://user-images.githubusercontent.com/4837554/151057389-9c21d1d7-6f0a-470e-adbd-f47e430ab4b9.png">

The user can click on them in search results, and would see:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/4837554/151047210-b03d6a3d-0d20-4fe3-809a-df92e0efb286.png">

If I remove them from the list of active books that determines metadata return, however, as I need to do, I think PaDS is going to be unhappy.  I assume it would revert back to one of the messages about not being found in PaDS.

It seems to me the best solution would be to stop asking PaDS about user permissions for offsite materials.  An easy fix on my end.

This means:
1) These books would not come back in the content metadata calls
2) Any article (there are some of those too) or book (the above two) in the offsite set would automatically be assigned no-full-text permissions by the server, and there would be no need to call PaDS to ask.

Since we are so close to going live, I wanted to double check: does this impact PaDS in any way I'm not anticipating?  (I don't think so, but checking anyway!)

**Comment by nrshapiro** [comment]
Testing the proposed fix on my local machine.  

Here's what it looks like to Test7 when preferences are set to preview window:

![2022-01-25_16h05_01](https://user-images.githubusercontent.com/4837554/151059805-91f24c03-0a42-49ce-a7b0-d21d11630ed8.jpg)

And if preferences are set to automatically jump to the read pane:

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/4837554/151059727-3aacf99a-6418-4138-bcac-6834f2d2abcc.png">

This looks good at least from my end!

**Comment by jwoosnam** [comment]
I am not sure I can add much to this. When I try and look at one of these
documents PaDS is not being asked about it.

**Comment by nrshapiro** [comment]
@jwoosnam 

Yes, sorry--since I am still trying to have a single version up long enough for a lot of testing, I pushed the change to stage last night.  So it's not asking anymore.  But if that change -- not asking PaDS -- doesn't seem to affect anything you NEED to know about via that call, then all is well.
