### ISSUE TITLE
Admin Privileges

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PaDS#4]
Looking down the road a few alphas, we will need to have some user accounts logging into the client flagged with Admin privileges so they may do the tasks in the **_Admin_** section of the client app which allows configuration of the settings.  I presume that's already built into PaDS because I know some accounts (I have one) can see reports etc.

But as part of your handshaking with the Client, PaDS will eventually need to communicate that a login/user has special **_Admin_** privileges to the client.  That's a month or so down the road I would guess, depending on the client development progress.

**Comment by jwoosnam** [comment]
As of PaDS v06.04h users with Company Admin privileges to PEP on PaDS can use their logon on the new client and will get admin privileges which initially will give them access to all PEPweb content.
