### ISSUE TITLE
User client settings tweaks

### ISSUE THREAD

**Issue by billdami** [Psychoanalytic-Electronic-Publishing/PaDS#6]
It looks like, for the current endpoint in the docs, the `GET /Users` endpoint has a typo for the client settings field, `CleintSettings`. 

https://app.swaggerhub.com/apis/JWoosnam/PEPSecure/1.02#/developers/getUsers

Also, I noticed this field is currently defined as a `string`. Is there any chance we could have that accept and return an actual freeform JSON object? E.g.
```
{
    "UserId": 0,
    "UserName": "string",
    "UserType": "Individual",
    "SubscriptionEndDate": {},
    "Branding": true,
    "ClientSettings": {
        "foo": 123,
        "bar": "abc"
    },
    "ReasonId": 401,
    "ReasonStr": "IJP.082.0215A"
  }
```

If this is not feasible, or too much work, that is OK, we can make adjustments in the frontend to manually serialize/deserialize to and from a raw string value when saving and retrieving user objects.

Also, do we know what the endpoint will look like yet for updating users' client settings? Ideally, we'd prefer something like:
```
PUT (or PATCH) /Users/{UserId}

Body:
{
    "UserId": 123,
    "ClientSettings": { ... }
}
```
(response body should return the same as the request body, or the full updated user object)

**Comment by jwoosnam** [comment]
Thanks Bill.  I have adjusted Github for the typo and ClientSettings and will add a Users PUT in due course.

**Comment by billdami** [comment]
@jwoosnam Thanks James. I also noticed a possible issue with the current `GET /Users/?SessionId={string}` endpoint on the stage site:

After logging in with the 'Test4' user, I attempt to make a request to that endpoint with:
```
https://stage-pads.pep-web.rocks/PEPSecure/api/v1/Users/?SessionId=22153647-FCF3-4BA2-82B6-A856E83B610B
```
And get back:
```xml
<Error>
    <Message>No HTTP resource was found that matches the request URI 'https://stage-pads.pep-web.rocks/PEPSecure/api/v1/Users/?SessionId=22153647-FCF3-4BA2-82B6-A856E83B610B'.</Message>
    <MessageDetail>No action was found on the controller 'Users' that matches the name 'DefaultAction'.</MessageDetail>
</Error>
```

Should this endpoint be working on staging yet?

**Comment by jwoosnam** [comment]
The new definition as described in Github wont be on stage until next week.
James

**Comment by jwoosnam** [comment]
@billdami I new version of the API has now been released to Stage.  This should now correspond to the swaggerhub definition

**Comment by billdami** [comment]
@jwoosnam see my comment on #7 it appears that endpoint is returning XML, and might not have the proper CORS headers set.

**Comment by billdami** [comment]
@jwoosnam thanks for resolving the CORS issue on the /Users?SessionId endpoint. Regarding the JSON vs XML, yeah I didn't realize XML was the default if no content-type header was provided, so once I got the endpoint working in the app, which is already sending the `application/json` value, it returned in the correct format.

It looks like the `POST /PEPSecure/api/v1/Users/Logout/` logout endpoint might have the same missing CORS header issue though, at least i got a similar error on my first test of that.

**Comment by billdami** [comment]
@jwoosnam it looks like the same CORS issue might be affecting the `PUT /PEPSecure/api/v1/Users/` endpoint as well. Also, does this request look correct to you for updating the user client settings? Its a bit hard to tell as the swagger docs dont show an example body content that i could see:

```
PUT https://stage-pads.pep-web.rocks/PEPSecure/api/v1/Users/?SessionId=ABC-123

//REQUEST BODY:
{
    "ClientSettings": { "preferencesVersion":"0.0.0", "theme":"default", "lang":"en-us" }
}
```
Or do you need any other fields in the request body json, such as the `UserId`?

**Comment by jwoosnam** [comment]
@billdami 
CORS should be OK for these URLs: http://gavant.pep-web.rocks:4200, https://stage.pep-web.rocks.  Are you using a different one?

PUT is as follows:  UserId in query string and SessionId and ClientSettings in body.
<img width="866" alt="Screenshot 2020-09-21 at 11 38 52" src="https://user-images.githubusercontent.com/70103034/93757705-21c4cf80-fbff-11ea-8e48-694dd37fab80.png">

**Comment by billdami** [comment]
Thanks @jwoosnam. Looks like the CORS errors were just a result of me using the endpoints incorrectly, for the PUT /Users I was sending the SessionId in the query string instead of the body. And for the POST /Logout I was sending the SessionId in the body instead of the query string. 😄

Looks like in the swagger docs for the PUT endpoint you had a comment detailing the correct structure so that's my mistake. However looks like the SessionId field is incorrectly specified as `"(query)"` below that, just an fyi:
<img width="607" alt="Screen Shot 2020-09-21 at 8 40 08 AM" src="https://user-images.githubusercontent.com/611458/93768699-c89d7180-fbe7-11ea-8c39-98cf721ec666.png">

Also, are you able to add example Request Body for endpoints in this swagger documentation? @nrshapiro has that for many endpoint in his docs, for example here, which are very helpful:

https://stage-api.pep-web.rocks/docs#/Database/database_advanced_search_v2_Database_AdvancedSearch__post
