### ISSUE TITLE
PEP Secure PaDS v06.04e - Released to stage

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PaDS#7]
I have just released an updated version of the pep secure API. 

The biggest change is that authenticate no longer excepts a GET, only a POST, with the user ID and password as part of the body.  Also there is an Authenticate/IP, which returns just the session Id if the IP address is not known.

It also updates the users API to allow the reading and writing of client settings.

 [Swagger](https://app.swaggerhub.com/apis/JWoosnam/PEPSecure/1.02) Is up to date although I am unsure of some of the syntax.

**Comment by billdami** [comment]
@jwoosnam it looks like on current stage, the new /Users/?SessionId={string} endpoint is returning XML for successful requests instead of JSON, and it may not have the correct CORS Access-Control-Allow-Origin header either, not 100% sure on that part though.

**Comment by jwoosnam** [comment]
@billdami Yes I had missed CORS on the Users API.  That should now be working. 
In terms of outputting XML I think this is Microsoft being too clever in that it can out put whatever you like.  If you add a header Accept: application/json it should work, or even Content-Type: application/json.  There must be a way to set the default output but I haven't found it yet.

**Comment by jwoosnam** [comment]
@billdami @adistasio @adistasio 
With a lot of help from Neil the SwaggerHub definition is now up to date.
[PEPSecure v1.02](https://app.swaggerhub.com/apis/nrshapiro/PEPSecure/1.02)

**Comment by jwoosnam** [comment]
@billdami @adistasio @nrshapiro 
Latest documentation can be found in:
[PEP Secure 1.03](https://app.swaggerhub.com/apis/nrshapiro/PEPSecure/1.03)

**Comment by nrshapiro** [comment]
@jwoosnam 

Can you please update the permits call in Swagger with the new ReasonForCheck parameter...thanks.
