### ISSUE TITLE
Permit request returns 401 error

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PaDS#8]
@jwoosnam 

Why does the permit request, such as:

https://padstest.zedra.net/PEPSecure/api/v1/Permits?SessionId=6C6584F4-7B7A-4D8B-910A-7B1C0F156AD6&DocId=JOAP.063.0667A&DocYear=2018&ReasonForCheck=AbstractView

return a 401 unauthorized error?

It returns successful permit information.

I think it should return 200 (Ok).  The permit request succeeded.  (Yes, the user's session is not authenticated, but that has nothing to do with the request for permit.)  I was checking to make sure the request was accepted, but it's rejected with 401, rather than returning response.ok (200)

**Comment by jwoosnam** [comment]
@nrshapiro Hi Neil, I have been looking at this but I don't understand the question.  If it is an unauthenticated session then I think it should return on authorised.

**Comment by nrshapiro** [comment]
@jwoosnam  - but the HTTP response 200 (ok) or 401 (unauthorized) refers to the request, not the true or false nature of the data requested.  

What the HTTP code you are returning is for is to show the status of the API request itself.  Not the session status.

Did the call succeed?

Or think of it this way.  The permit request is a server (or client) asking you about a particular session.  It may or may not be the only session it's managing.  But the call to request the information certainly succeeded.

To my reading, the 401 return means the call was rejected--the server is not authorized to request the information.  But in fact the call succeeded...the server asked for information and you returned it.  Whether or not the permit is available is the subject of the return content, not the subject of the call.

So: basically, you told my server that it was unauthorized to request the permit information, and you are rejecting the call.  So my server took that as a no, and produced an error exception in return.  Can't get that information, I'm unauthorized.

But the call actually succeeded, hence the OK response I believe it should return.

The server, for example, would return 401 Unauthorized if an unauthenticated client made a call to an endpoint that required login to perform an action or request information.  It's saying, _no, you don't have permission to make that endpoint call i.e., to perform an action.._

Another example case:  I am logged in as a non-admin, but I make a endpoint call to delete a resource.  That's unauthorized.  Or I make a endpoint call to update admin information: Unauthorized.  

```
The HTTP 401 Unauthorized client error status response code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.

This status is sent with a WWW-Authenticate header that contains information on how to authorize correctly.

This status is similar to 403, but in this case, authentication is possible.
```

**Comment by jwoosnam** [comment]
@nrshapiro I suppose it depends on which way you look at it. As far as I was concerned that session was not authorised to do a permit request therefore I returned Unauthorised.  I am using the same logic for my authenticate requests. If the request has an invalid username or password, or does not have a valid subscription, I pass back unauthorised.
Of course I can change this, but to be consistent I would need to change it for all my calls which may cause the client some problems.

**Comment by nrshapiro** [comment]
Remember, it's the server maknig the call--it's authorized to do so and the call actually succeeds (whereas Unauthorized suggests that it didn't).  But I've already worked around it.  So it's not a problem for the server.  I just think it's not correct from the Restful API conversation protocol.
