### ISSUE TITLE
session Id for a non-logged-in user

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PaDS#9]
As I convert the server over to "All PaDS" authentication (used, for example, when the server is also the client, like in the Docs/ interface to it), the issue came up as to "how to get a session id" for a non-logged in user.

I didn't see any way, so I just sent in a login request for the "dummy" account I was recording before when I did my own server authentication...username "NotLoggedIn".  I give it password "NoPass", and let it reject me...but the rejection includes a session id, so I can use that.

Is that the right way you want clients to get a session id  for a non-logged-in user?

**Comment by jwoosnam** [comment]
@nrshapiro Gavant call the IP endpoint which either logs them on or just returns an session Id:
https://stage-pads.pep-web.rocks/pepsecure/api/v1/authenticate/ip

**Comment by nrshapiro** [comment]
@jwoosnam ok, I've done it that way.  You might want to document that.  And you could consider adding a new session endpoint of some sort.
